[project]
name = "min-dados"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.1.10",
    "google-genai>=1.46.0",
    "lxml>=6.0.2",
    "mcp>=1.21.0",
    "nest-asyncio>=1.6.0",
    "ollama>=0.6.0",
    "openai>=2.7.1",
    "pandas>=2.3.3",
    "playwright>=1.55.0",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.5",
    "tabulate>=0.9.0",
    "yfinance>=0.2.66",
]
